### ISSUE TITLE
機能リクエスト:  FireFox版

### ISSUE THREAD

**Issue by Kdroidwin** [k0range/video2article-next#1]
manifest.json の修正を行うことで可能だと思います。

**Comment by k0range** [comment]
提案ありがとうございます！

フレームワークを使っているのでほとんど修正なしで対応できるかもしれないです。

**Comment by Kdroidwin** [comment]
楽しみにしております。

**Comment by k0range** [comment]
バージョン1.1.1でFirefoxに対応し、本日Firefoxのアドオンストアに追加されました。

https://addons.mozilla.org/ja/firefox/addon/video-to-article-next/
