### ISSUE TITLE
バグ：SponserBlock との干渉

### ISSUE THREAD

**Issue by Kdroidwin** [k0range/video2article-next#2]
SponsorBlock for YouTube - 動画の広告シーンを自動スキップを有効にしているとこのアドオンが機能しない

動作環境 Floorp 最新版(FirefoxESRベース)

**Comment by Kdroidwin** [comment]
また、一度Sponserblockをオフにした状態ではこのアドオンで要約することはできるが、Sponserblockを有効にすると、画面にモザイクがかかるだけで、有効にするほどまであって要約のポップアップが消える。

**Comment by k0range** [comment]
報告ありがとうございます。

同等の現象をこちらでも確認しました。CSSのアニメーション名が被っていることが原因のようです。

近日中に修正をリリースする予定です、今しばらくお待ちください

**Comment by k0range** [comment]
修正を含めたバージョン1.1.2をリリースしました。

アドオンストアでの審査が完了次第、ご利用いただけるようになります。
