### ISSUE TITLE
 機能リクエスト: ショートカットキーで記事に変換

### ISSUE THREAD

**Issue by Kdroidwin** [k0range/video2article-next#22]
ショートカットキー(自分で設定)で拡張機能のクリックを実行し記事に変換する。

**Comment by k0range** [comment]
時間がかかってしまい申し訳ないです！
バージョン1.3.0 で追加しました。アドオンストアでの審査が完了次第ご利用いただけるようになります。

**Comment by Kdroidwin** [comment]
ありがとうございます。
