### ISSUE TITLE
機能リクエスト: Escキーでポップアップを閉じる

### ISSUE THREAD

**Issue by Kdroidwin** [k0range/video2article-next#3]
Escキーを押すことで記事のポップアップを閉じる(Close)
この機能が不要なユーザーがいるかもしれないので、オプション(自由に選択)でお願いします。

**Comment by k0range** [comment]
この機能を追加したバージョン1.2.0をリリースしました。

アドオンストアでの審査が完了次第、ご利用いただけるようになります。
